os: windows
language: sh
python:
- '3.8'
before_install:
- git config --local user.name "Ming Yen Hsieh"
- git config --local user.email "mhsieh28@my.bcit.ca"
- choco install python3
- export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
- python -m pip install --upgrade pip wheel
- python -m pip install --extra-index-url https://pypi.org/project/pytest/ pytest
- python -m pip install --extra-index-url https://pypi.org/simple/ pygame
- python -m pip install --extra-index-url https://pypi.org/project/cx-Freeze/ cx-Freeze
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
- python setup.py build
- 7z a build.zip build
virtualenv:
  system_site_packages: true
deploy:
  provider: releases
  api_key: 7d9d13a0580c641e3d30ac22046259d4e07a3bc8
  file: build.zip
  on:
    repo: bakedSpaceTime/ACIT-2911-PROJECT
  skip_cleanup: 'true'
