os: windows
language: sh
python:
  - '3.8'
before_install:
  - choco install python3
  - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
  - python -m pip install --upgrade pip wheel
  - python -m pip install --extra-index-url https://pypi.org/project/pytest/ pytest
  - python -m pip install --extra-index-url https://pypi.org/simple/ pygame
  - python -m pip install --extra-index-url https://pypi.org/project/cx-Freeze/ cx-Freeze
install:
  - pip install -r requirements.txt
script:
  - echo "skipping tests"
virtualenv:
  system_site_packages: true  