# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
#         - uses: actions/checkout@v2
#         - name: Install dependencies
#           run: |
#             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
        - name: Build Executable
          run: python setup.py build
      
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2
          with:
            # Artifact name
            name: Pandemic Run Excecutable
            # A file, directory or wildcard pattern that describes what to upload
            path: build/exe.*
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}      
    
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
        
    - name: Build Executable
      run: .\python setup.py build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Pandemic Run Excecutable
        # A file, directory or wildcard pattern that describes what to upload
        path: build/exe.*

#     - name: Test with pytest
#       run: |
#         pytest
